### PR TITLE
del

### PR DESCRIPTION
**Pull request by robpierini**

### CODE REVIEW

**Comment by SkullCrusher** [comment]
I am not sure exactly but if this is deleting my files like it looks please dont.

**Comment by SkullCrusher** [comment]
You removed my git files bud.

**Comment by DallasP9124** [comment]
No I didn’t, I just checked my pushes and didn’t see your name being deleted anywhere? Which commit on which day did I do it?

**Comment by SkullCrusher** [comment]
Please look at the changes tab, it appears to be removing my file and Haiden's

**Comment by karcaw** [comment]
It does look like two files will be removed in this merge.

**Comment by DallasP9124** [comment]
yes i see but I dont see how I did it though, I never removed anything when I committed my changes and no merge conflicts came up so I dont even know what happened?

**Comment by DallasP9124** [comment]
wait are you even talking to me or are you talking to rob?

**Comment by TRByers** [comment]
It's shows all of your files still. I don't know what you mean. At least it does in the runme script. But I didn't delete anything when I went through

On Oct 17, 2015 8:53 PM, David M Harkins <notifications@github.com> wrote:
You removed my git files bud.

---

**Pull request closed without merging**
